Search.appendIndex(
    [
                {
            "fqsen": "\\BD",
            "name": "BD",
            "summary": "",
            "url": "classes/BD.html"
        },                {
            "fqsen": "\\BD\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BD.html#method___construct"
        },                {
            "fqsen": "\\BD\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/BD.html#method___destruct"
        },                {
            "fqsen": "\\BD\u003A\u003A_consultar\u0028\u0029",
            "name": "_consultar",
            "summary": "",
            "url": "classes/BD.html#method__consultar"
        },                {
            "fqsen": "\\BD\u003A\u003A_ejecutar\u0028\u0029",
            "name": "_ejecutar",
            "summary": "",
            "url": "classes/BD.html#method__ejecutar"
        },                {
            "fqsen": "\\BD\u003A\u003A_ultimoId\u0028\u0029",
            "name": "_ultimoId",
            "summary": "",
            "url": "classes/BD.html#method__ultimoId"
        },                {
            "fqsen": "\\BD\u003A\u003AGetError\u0028\u0029",
            "name": "GetError",
            "summary": "",
            "url": "classes/BD.html#method_GetError"
        },                {
            "fqsen": "\\BD\u003A\u003AError\u0028\u0029",
            "name": "Error",
            "summary": "",
            "url": "classes/BD.html#method_Error"
        },                {
            "fqsen": "\\BD\u003A\u003A\u0024con",
            "name": "con",
            "summary": "",
            "url": "classes/BD.html#property_con"
        },                {
            "fqsen": "\\BD\u003A\u003A\u0024error",
            "name": "error",
            "summary": "",
            "url": "classes/BD.html#property_error"
        },                {
            "fqsen": "\\ClientesBD",
            "name": "ClientesBD",
            "summary": "",
            "url": "classes/ClientesBD.html"
        },                {
            "fqsen": "\\ClientesBD\u003A\u003AInsertar\u0028\u0029",
            "name": "Insertar",
            "summary": "",
            "url": "classes/ClientesBD.html#method_Insertar"
        },                {
            "fqsen": "\\ClientesBD\u003A\u003AModificar\u0028\u0029",
            "name": "Modificar",
            "summary": "",
            "url": "classes/ClientesBD.html#method_Modificar"
        },                {
            "fqsen": "\\ClientesBD\u003A\u003ABorrar\u0028\u0029",
            "name": "Borrar",
            "summary": "",
            "url": "classes/ClientesBD.html#method_Borrar"
        },                {
            "fqsen": "\\ClientesBD\u003A\u003ASeleccionar\u0028\u0029",
            "name": "Seleccionar",
            "summary": "",
            "url": "classes/ClientesBD.html#method_Seleccionar"
        },                {
            "fqsen": "\\ClientesBD\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/ClientesBD.html#property_id"
        },                {
            "fqsen": "\\ClientesBD\u003A\u003A\u0024nombre",
            "name": "nombre",
            "summary": "",
            "url": "classes/ClientesBD.html#property_nombre"
        },                {
            "fqsen": "\\ClientesBD\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/ClientesBD.html#property_email"
        },                {
            "fqsen": "\\ClientesBD\u003A\u003A\u0024filas",
            "name": "filas",
            "summary": "",
            "url": "classes/ClientesBD.html#property_filas"
        },                {
            "fqsen": "\\SERVIDOR",
            "name": "SERVIDOR",
            "summary": "",
            "url": "namespaces/default.html#constant_SERVIDOR"
        },                {
            "fqsen": "\\USUARIO",
            "name": "USUARIO",
            "summary": "",
            "url": "namespaces/default.html#constant_USUARIO"
        },                {
            "fqsen": "\\CONTRASENA",
            "name": "CONTRASENA",
            "summary": "",
            "url": "namespaces/default.html#constant_CONTRASENA"
        },                {
            "fqsen": "\\BASEDATOS",
            "name": "BASEDATOS",
            "summary": "",
            "url": "namespaces/default.html#constant_BASEDATOS"
        },                {
            "fqsen": "\\obtenerSaludo\u0028\u0029",
            "name": "obtenerSaludo",
            "summary": "Obtiene\u0020un\u0020saludo\u0020en\u0020funci\u00F3n\u0020de\u0020la\u0020hora\u0020actual.",
            "url": "namespaces/default.html#function_obtenerSaludo"
        },                {
            "fqsen": "\\saludoAntiguo\u0028\u0029",
            "name": "saludoAntiguo",
            "summary": "Funci\u00F3n\u0020obsoleta\u0020de\u0020ejemplo.",
            "url": "namespaces/default.html#function_saludoAntiguo"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
